### ISSUE TITLE
Crash on server load on 1.16

### ISSUE THREAD

**Issue by gglobensky** [iChun/MultiplayerServerPause#1]
Hi, I just tried your mod in my modpack and noticed the server crashes on startup. 
I am using FML 36.2.8 with Minecraft 1.16.5 and Multiplayer-Server-Pause-1.16.5-Forge-1.0.0.

Here is the crashlog :
https://pastebin.com/kwheQH9k

I am using Roadrunner, if it helps pinpoint the issue.

**Comment by iChun** [comment]
That's what I get for testing the mod on Fabric 😂

I'll have this fixed up and posted on CurseForge soon

**Comment by iChun** [comment]
Fixed versions are up on CurseForge. Thanks for the issue report!
