### ISSUE TITLE
Error opening MC server

### ISSUE THREAD

**Issue by 13947312448** [iChun/MultiplayerServerPause#15]
[latest.log](https://github.com/iChun/MultiplayerServerPause/files/14566479/latest.log)

**Comment by iChun** [comment]
You'll have to use a fabric loader version of 0.14.x. 0.15 changed some stuff that broke complete config. They are aware of this issue but a fix is only for newer versions of Minecraft as fabric loader 0.15 became mainstay in MC 1.20.2+. Most of your mods on 1.19.4 will work fine on fabric loader 0.14.
