### ISSUE TITLE
Compatibility with Valkyrien Skies 2

### ISSUE THREAD

**Issue by ARitz-Cracker** [iChun/MultiplayerServerPause#20]
I've spoken with one of the developers of Valkyrien Skies 2, in turns out that its physics thread indeed must be notified of when the server's paused. They linked me to the snippet of code of where this is handled in single player:

https://github.com/ValkyrienSkies/Valkyrien-Skies-2/blob/cf2626161b3185c4e337ac3904778859727894dd/common/src/main/java/org/valkyrienskies/mod/mixin/client/MixinMinecraft.java#L122

With the following suggestion
> suggest to use `VSGameUtilsKt.getShipObjectWorld(server)` as opposed to the `IShipObjectWorldServerProvider` that this method uses

**Comment by iChun** [comment]
Try 1.3.2. I've tried to make sure VS knows the dedicated server is paused when I do pause the server and from my small tests it doesn't flood the console anymore so I assume it's working fine. Let me know if there's any issues.

**Comment by ARitz-Cracker** [comment]
Seems to work for me!
