### ISSUE TITLE
crash when opening escape menu

### ISSUE THREAD

**Issue by merasmus44** [iChun/MultiplayerServerPause#5]
Game crashes when going to the escape menu after loading a world. 
I'm pretty sure it originates from this mod.

**Log files**
log file [log](https://gist.github.com/merasmus44/fec0cb58f40a3338b28f8db3667975c9#file-latest-log)
crash log file [log](https://gist.github.com/merasmus44/c9b2f075ba3667892b599c3a0d8dd475#file-crash-2023-06-13_15-34-26-server-txt).

**Versions**
- Minecraft version : 1.19
- Fabric version: fabric-loader-0.14.18-1.19

**Other mods**
completeconfig 2.0.0
modmenu 4.0.4
better_respawn 1.19-2.0.0

**Comment by iChun** [comment]
Sorry for the delay in responding but your crash log suggests that it is better respawn causing the crash, not MSP. Might be a bit late for that though you'd probably have figured it out by now
