### ISSUE TITLE
[Modpack] 1.18.2 seems to randomly crash on entity tick, stacktrace lists this mod

### ISSUE THREAD

**Issue by xFirefalconx** [iChun/MultiplayerServerPause#7]
I do not have full proof here! But I am currently investigating a serverside (client in singleplayer or open LAN is confirmed to crash) "ticking entity" crash and this mod is on the last spot of the stacktrace. 
I am not an expert in reading stacktrace - so if you find somebody who is doing something wonky instead, please let me know and why you think so, so I can report and hopefully get a fix update.

Forge 40.2.10
MC 1.18.2
Mod 1.1.0

Crash happens since a while in my modpack and it's hard to reproduce, however **if the entity density is higher, it is happening more likely**. 
You can test it by using my currently latest "1.1b05" version of "Royal Equines: Petrified Magic", spawn a large amount of entities and just wait. 

### What is happening exactly: 
You're logged in a world, singleplayer or multiplayer doesn't matter in my case. All of the sudden, you might be moving around or just idling, the game starts to freeze entirely, "no response" shows up in the task bar. If you wait patiently, the game will react again, but it has crashed, sending you to the server page?? With an error message. You can re-join the game without any problems, but it can and will happen again, in due time. 
The log will show a specific entity, happened already with (untamedwilds:newt, minecraft:villager, minecraft:cow, minecraft:iron_golem, ...) a lot of different entities. It's not the player though! (As far as I could decipher the logs)
It doesn't corrupt the worlds but it does heavily impact the flow and playability of a pack. 
I am doing a reverse debugging and disabling mods that *might* cause it and hope to nit have an issue after a prolongued time. This is very inefficient so I hope you got an idea about what's going on. Or know someone who does. 

My findings so far are that since I disabled this mod there have been less crashes with ticking entity involved. I tested with ... a bunch of rabbits (see screenshots below), a village nearby, some naturally spawned critters. I reloaded the scene... it's unreliable to say whether it happens again, yet didn't have the same crash but it might need more time? Unsure. 
However, I had a "ticking entity" crash involving shift+F3 from spark while having Multiplayer Pause active, which ... seems to have triggered on an other save?? Uhhh.... And that crash was happening immediately after I pressed shift+F3, or a little bit after an entity ticked. Something is amiss here, I can smell it. I just don't know if it's your mod for certain. 

I collected a LOT of crash messages. Maybe there's a common fault here. 

[crash-2023-10-20_15.39.35-server.txt](https://github.com/iChun/MultiplayerServerPause/files/13184389/crash-2023-10-20_15.39.35-server.txt)
[crash-2023-10-27_00.26.53-server.txt](https://github.com/iChun/MultiplayerServerPause/files/13184390/crash-2023-10-27_00.26.53-server.txt)
[crash-2023-10-27_00.45.53-server.txt](https://github.com/iChun/MultiplayerServerPause/files/13184391/crash-2023-10-27_00.45.53-server.txt)
[crash-2023-10-27_01.04.47-server.txt](https://github.com/iChun/MultiplayerServerPause/files/13184392/crash-2023-10-27_01.04.47-server.txt)
[crash-2023-10-13_00.26.31-server.txt](https://github.com/iChun/MultiplayerServerPause/files/13184393/crash-2023-10-13_00.26.31-server.txt)
[crash-2023-10-14_06.18.20-server.txt](https://github.com/iChun/MultiplayerServerPause/files/13184394/crash-2023-10-14_06.18.20-server.txt)
[crash-2023-10-16_02.25.58-server.txt](https://github.com/iChun/MultiplayerServerPause/files/13184395/crash-2023-10-16_02.25.58-server.txt)

Also, have my latest.logs: 

[2023-10-27-2.log](https://github.com/iChun/MultiplayerServerPause/files/13184410/2023-10-27-2.log) (iirc your mod is on here)
[2023-10-27-3.log](https://github.com/iChun/MultiplayerServerPause/files/13184405/2023-10-27-3.log) (iirc your mod is on here)

[latest.log](https://github.com/iChun/MultiplayerServerPause/files/13184413/latest.log) (without your mod)

Most recent:
[latest.log](https://github.com/iChun/MultiplayerServerPause/files/13184756/latest.log)
[crash-2023-10-27_02.50.08-server.txt](https://github.com/iChun/MultiplayerServerPause/files/13184757/crash-2023-10-27_02.50.08-server.txt)

![grafik](https://github.com/iChun/MultiplayerServerPause/assets/106652912/127b8aac-cf41-4ce9-a147-12adbf5689da)
![grafik](https://github.com/iChun/MultiplayerServerPause/assets/106652912/dc826d0b-aeda-42fa-b0a1-aa201990f419)

**Comment by iChun** [comment]
Hello,

Apologies for the delay in responding, Life has been busy, the usual.

I hope you've managed to trace down the cause of your crashes. I've had a look at your logs and the stacktraces do not suggest MSP is at fault, MSP is mentioned because it has mixin-ed a class involved in the stacktrace. 

One of the classes suggests a crash is happening with whichever mod adds: `tallestegg.guardvillagers.entities.ai.goals.VillagerGossipToGuardGoal` 

and the other stack trace is a CME error when selecting entities in a setting, which MSP doesn't even come remotely close to. 

It's also aided by the fact that removing this mod from your pack doesn't stop the crashes from happening. Whilst a crucial step in trying to figure out if mods are causative or not, a presumed appearance of reduction of crashes, without proper identification of the causes (eg reading the stack trace), and not total elimination of crashes, doesn't really mean anything. 

If you feel like MSP is still the culprit for the crashes, please feel free to reply below, but if otherwise I am marking this issue closed.

**Comment by xFirefalconx** [comment]
Thank you for the information. I haven't had any luck yet but I know the mod it *might* stem from so I referenced the issue on their github. I'm grateful for your help despite it seems I reported to the wrong person. Hopefully we'll have found the culprit soon.
