### ISSUE TITLE
Server Crash (Fabric 0.15.1, MC 1.20.1)

### ISSUE THREAD

**Issue by xllifi** [iChun/MultiplayerServerPause#8]
Fabric 0.15.1
MC 1.20.1

Mods:
Fabric API 0.91.0
CompleteConfig 2.5.0
Ping Wheel 1.7.0
MultiplayerServerPause 1.1.0

Stacktrace: https://hst.sh/uguhexekez.log

**Comment by xllifi** [comment]
Changing Fabric loader to 0.14.25 fixed the issue. Though some mods are already using 0.15.1, so this is still an issue

**Comment by iChun** [comment]
It's an issue with Complete Config, urge them to push an update on the version you require. They are aware of the issue: https://github.com/Lortseam/completeconfig/issues/22
